import { Skin } from "theme.slint";
import { SpaceWeatherDataWidget, SpaceWeatherAdapter, KpIndex } from "space_weather_widget.slint";
import { IndoorDataWidget, IndoorAdapter } from "indoor_widget.slint";
import { VideoWidget, VideoAdapter } from "video_widget.slint";
import { AboutSlint, Button, HorizontalBox, VerticalBox } from "std-widgets.slint";

export { IndoorAdapter, SpaceWeatherAdapter, VideoAdapter }


component BoxBase inherits Rectangle {
    background: Skin.palette.boxBgnd;
    border-radius: 15px;
}

component TitledBox inherits BoxBase {
    in property <string> title;

    VerticalLayout {
        if (root.title != "") : Text {
            text <=> root.title;
            font-size: Skin.TitleFont;
            font-weight: 700;
        }
        spacing: 10px;
        padding: 15px;

        @children
    }
}

component SpaceWeatherWidget inherits TitledBox {
    title: "Space weather";

    SpaceWeatherDataWidget { }
}

component IndoorWidget inherits TitledBox {
    title: "Indoor";

    IndoorDataWidget { }
}

component OutdoorVideo inherits TitledBox {
    title: "Outdoor live video";

    VideoWidget {}
}

component AboutWidget inherits PopupWindow {
    BoxBase {
        HorizontalBox {
            alignment: center;
            y: 7px;
            horizontal-stretch: 1;
            VerticalBox {
                alignment: center;
                AboutSlint { }
            }
        }
    }
}

component MainContent {
    min-width: 600px;
    min-height: 1024px;
    max-width: 600px;
    max-height: 1024px;
    preferred-width: 600px;
    preferred-height: 1024px;

    Rectangle {
        background: Skin.palette.mainContent;
    }

    GridLayout {
        spacing: 2px;

        SpaceWeatherWidget {
            row: 0; col: 0;
        }

        OutdoorVideo {
            row: 1;
        }
        IndoorWidget {
            row: 2;
        }
    }

    aboutwidget := AboutWidget {
        width: parent.preferred-width;
        height: parent.preferred-height/3;
    }
   
    Button {
        y: 7px;
        x: root.preferred-width - 120px;
        text: "About";
        icon: @image-url("images/slint-logo-small-light.svg");
        clicked => { aboutwidget.show(); }
    }
}

export component AppWindow inherits Window {
    always-on-top: true;
    background: #7c7c7c;
    min-width: 600px;
    min-height: 1024px;
    max-width: 600px;
    max-height: 1024px;
    preferred-width: 600px;
    preferred-height: 1024px;

    no-frame: true;

    MainContent {}
}
