// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { VerticalBox, Palette } from "std-widgets.slint";

export global VideoAdapter {
    in property <image> video-frame;
    in property <bool> playing;
}

export component VideoWidget inherits Rectangle {
    in property <image> video-frame <=> VideoAdapter.video-frame;
    in property <bool> playing <=> VideoAdapter.playing;
    
    preferred-height: 500px*(9/16);
    background: #000000;

    pure callback toggle-pause-play();

    states [
        shown when area.has-hover || animation-tick() < 5s : {
            controls.opacity: 1;
            in {
                animate controls.opacity {
                    duration: 50ms;
                }
            }
        }
        hidden when !area.has-hover: {
            controls.opacity: 0;
            in {
                animate controls.opacity {
                    delay: 3s;
                    duration: 500ms;
                }
            }
        }
    ]

    VerticalBox {
        Image {
            source: video-frame;
        }
    }

    area := TouchArea {
        width: 50%;
        height: self.preferred-height;
        y: root.height - self.height - 40px;
        controls := Rectangle {
            border-radius: 4px;
            background: Palette.color-scheme == ColorScheme.dark ? #3737378c : #ffffff82;

            Image {
                width: 64px;
                height: 64px;
                source: root.playing ? @image-url("images/pause.svg") : @image-url("images/play.svg");
            }

            TouchArea {
                clicked => {
                    root.toggle-pause-play();
                }
            }
        }
    }
}
