// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { VerticalBox, Palette } from "std-widgets.slint";

export global VideoAdapter {
    in property <image> video-frame;
    in property <bool> playing;
}

component VideoWidgetBase inherits VerticalLayout {
    padding: 1px;
    spacing: 1px;

    min-height: root.width * (9.0/16.0) * 0.85;

    Rectangle {
        background: #000000;
        border-radius: 15px;
        @children
    }
}

export component VideoWidget inherits VideoWidgetBase {
    in property <image> video-frame <=> VideoAdapter.video-frame;
    in property <bool> playing <=> VideoAdapter.playing;

    pure callback toggle-pause-play();

    states [
        shown when area.has-hover || animation-tick() < 5s : {
            controls.opacity: 1;
            in {
                animate controls.opacity {
                    duration: 50ms;
                }
            }
        }
        hidden when !area.has-hover: {
            controls.opacity: 0;
            in {
                animate controls.opacity {
                    delay: 3s;
                    duration: 500ms;
                }
            }
        }
    ]

    Rectangle {
        Image {           
            image-fit: ImageFit.preserve;
            source: video-frame;
        }
    }

    area := TouchArea {
        width: 50%;
        height: 50%;
        y: root.height - self.height - 40px;
        controls := Rectangle {
            border-radius: 8px;
            background: Palette.color-scheme == ColorScheme.dark ? #3737378c : #ffffff82;

            Image {
                width: 64px;
                height: 64px;
                source: root.playing ? @image-url("images/pause.svg") : @image-url("images/play.svg");
            }

            TouchArea {
                clicked => {
                    root.toggle-pause-play();
                }
            }
        }
    }
}
